[package]
name = "oplusbright"
version = "0.1.0"
edition = "2024"

[dependencies]
libc = "0.2"

[lib]
name = "oplusbright"
path = "src/lib.rs"

[[bin]]
name = "xia_display_adaptor"
path = "src/main.rs"

[profile.release]
opt-level = "s"
lto = "fat"
codegen-units = 1
panic = "abort"
strip = true
